source/Magritte-Model.package/MADescription.class/instance/addCondition.labelled.ifValid..st

Guard to prevent validation if specified field fails

[Enh]: Resolve #58 - Basic Condition Dependencies

---

source/Magritte-Model.package/MAMemento.class/instance/doesNotUnderstand..st
source/Magritte-Model.package/MAMemento.class/instance/readUsing..st

Mementos will try to match an element description from their model to respond to MNU

Fix #56 - Memento DNU Magic

---

source/Magritte-Model.package/MADynamicDescriptionCache.class/README.md
source/Magritte-Model.package/MADynamicDescriptionCache.class/properties.json

Easy one - clarify and fix grammar

[Doc]: Tweak MADynamicDescriptionCache class comment

---

source/Magritte-Model.package/Object.extension/instance/isSameAs..st
source/Magritte-Model.package/Object.extension/instance/isSameAs.using..st
source/Magritte-Model.package/Object.extension/instance/maHash.st
source/Magritte-Model.package/Object.extension/instance/maHashUsing..st

See `#isSameAs:` and `#maHash`

[Feature]: Resolve #60 - Comparison Based on Descriptions

---

source/Magritte-Model.package/MAActionDescription.class/instance/icon.st
source/Magritte-Model.package/MABlockDescription.class/class/defaultLineCount.st
source/Magritte-Model.package/MABlockDescription.class/instance/descriptionLineCount.st
source/Magritte-Model.package/MABlockDescription.class/instance/lineCount..st
source/Magritte-Model.package/MABlockDescription.class/instance/lineCount.st

[Bug]: Block Description Needs Line Count
Must be polymorphic with MAMemoDescription, otherwise DNU from MAMemoMorph

block-description-needs-linecount

---

source/Magritte-GT.package/GLMPresentation.extension/instance/glmAddSelectionActions.st
source/Magritte-GT.package/GLMPresentation.extension/properties.json
source/Magritte-Model.package/MAActionDescription.class/properties.json
source/Magritte-Model.package/MARelationDescription.class/instance/descriptionClasses.st
source/Magritte-Model.package/ManifestMagritteModel.class/README.md
source/Magritte-Model.package/ManifestMagritteModel.class/class/ruleRBBadMessageRuleV1FalsePositive.st
source/Magritte-Model.package/ManifestMagritteModel.class/properties.json
source/Magritte-Model.package/String.extension/instance/normalizeCamelCase.st
source/Magritte-Morph.package/MAActionDescription.extension/instance/buttonOn..st
source/Magritte-Morph.package/MACheckboxMorph.class/instance/buildMorphView.st
source/Magritte-Morph.package/MADescriptionMorph.class/instance/perform.orSendTo..st
source/Magritte-Morph.package/MAElementRow.class/instance/buildButton..st
source/Magritte-Morph.package/MAOneToManyMorph.class/instance/buildSelectButton.st
source/Magritte-Morph.package/MAOneToOneMorph.class/instance/buildSelectButton.st
source/Magritte-Morph.package/MARelationMorph.class/instance/buildClassChooser.st
source/Magritte-Morph.package/MARelationMorph.class/instance/buildMorph.st
source/Magritte-Morph.package/MARelationMorph.class/instance/buildMorphViewOn..st
source/Magritte-Morph.package/MATextMorph.class/instance/buildMorphView.st
source/Magritte-Morph.package/TokenCollectorMorph.class/instance/tokenViewer.st
source/Magritte-Morph.package/TokenMorph.class/instance/initialize.st
source/Magritte-Pharo7-Model.package/MorphicUIManager.extension/instance/chooseFile.in..st

code-critics

---

source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline330ForPharo..st

Update baseline to support Pharo 8

---

source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline310CommonExtDeps..st
source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline330ForPharo..st

Update old versions of Seaside and Grease

Update old versions

---

README.md

Doc explaining how to add Magritte as project dependency

---

source/Magritte-Glamour.package/GLMPresentation.extension/instance/glmAddSelectionActions.st
source/Magritte-Model.package/MAActionDescription.class/instance/^less.equals.st
source/Magritte-Model.package/MAActionDescription.class/instance/priority.st
source/Magritte-Model.package/Object.extension/instance/magritteActionDescriptions.st

[Enh]: Sort Actions by `#priority`
(just like other descriptions)

actions-sorting

---

source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline330ForPharo..st

[Bug]: Fix Magritte-Glamour Package Name

baseline-glamour-fix

---

source/Magritte-Bootstrap.package/MAAccessor.extension/instance/handlesSelector..st
source/Magritte-Bootstrap.package/MASelectorAccessor.extension/instance/handlesSelector..st
source/Magritte-Bootstrap.package/MASelectorAccessor.extension/properties.json
source/Magritte-Bootstrap.package/MAVariableAccessor.extension/instance/handlesSelector..st
source/Magritte-Bootstrap.package/MAVariableAccessor.extension/properties.json

Several methods were contained in both

[Bug]: Bootstrap Package Dirties Model

---

source/Magritte-Developer.package/MAElementDescription.extension/instance/addTo.as..st
source/Magritte-Developer.package/MASelectorAccessor.extension/instance/maSetUp..st

Must have missed this in original API change...

Port Lazy-Init Generated Code to New API

---

source/Magritte-Morph.package/MAOneToManyMorph.class/instance/buildMorphView.st
source/Magritte-Morph.package/MATokenCompletionMorph.class/instance/buildMorphView.st
source/Magritte-Morph.package/TokenCollectorMorph.class/instance/initialize.st

Large collections were difficult to view/work with

 To-Many Relations Should Be Scrollable

---

source/Magritte-Morph.package/MARelationMorph.class/instance/classes.st

[Bug]: Relation Class Sorting DNU

---

README.md

Chain of "this version is obsolete, please look there" leads me to Booklet-Magritte.

Readme: WIP Tutorial => Booklet-Magritte

---

source/Magritte-Model.package/MADescription.class/instance/write.to..st

[Enh]: #write:to: Convenience-Method

---

source/Magritte-Developer.package/MASelectorAccessor.extension/instance/maSetUp.for..st

Getter Generation should Use #maLazyInstVarUsing:

---

source/Magritte-GT/Symbol.extension.st
source/Magritte-Model/MAElementDescription.class.st
source/Magritte-Model/MAOptionDescription.class.st
source/Magritte-Model/Symbol.extension.st

Option String Writer Should Respect `#display:`

---

source/Magritte-Seaside/MAListCompositionComponent.class.st
source/Magritte-Seaside/MAMultipleOptionDescription.extension.st

fix typo in  MAListCompositonComponent

---

source/BaselineOfMagritte/BaselineOfMagritte.class.st

fixes #199
older Grease version caused some automatic deprecation rewrites

use Grease 1.7.x

---

source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-GToolkit/Object.extension.st

GT Form Inspector View

---

source/Magritte-GToolkit/MADropdownElement.class.st

Some methods in MADropdownElement

[Port]: GT Aptitude Leftovers

---

source/Magritte-Model/MADictionaryAccessor.class.st
source/Magritte-Model/MAPropertyAccessor.class.st

- Based on the key; very similar to Selector Accessor
- And some class comments

[Enh]: Default Labels for Dictionary Accessors

---

source/Magritte-GToolkit/MACompositeElementBuilder.class.st
source/Magritte-GToolkit/MADropdownElement.class.st
source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-Model/MAContainer.class.st

And some cleanups (e.g. whitespace, reorganize examples)

[Enh]: Bloc Form - Click on Field Label to Spawn Object

---

source/Magritte-GToolkit/MACompositeElementBuilder.class.st
source/Magritte-GToolkit/MADropdownElement.class.st
source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-Merging/MAPatchMacro.class.st
source/Magritte-Merging/MAPatchOperation.class.st
source/Magritte-Model/MAContainer.class.st

- Enable/disable operations
- Elements
- Auto-set oldValue from model
- instance creation message
- GT Example

[Enh]: Patch Operation & Macro View

---

source/Magritte-Model/MAObject.class.st
source/Magritte-Model/MATPropertyOwner.extension.st
source/Magritte-Model/MATPropertyOwner.trait.st

Generally useful in situations where subclassing is not convenient

MAObject Properties - Extract to Trait

---

source/Magritte-Merging-Bloc/MAPatchOperation.extension.st
source/Magritte-Merging/MAPatchMacro.class.st
source/Magritte-Merging/MAPatchOperation.class.st
source/Magritte-Merging/Object.extension.st

- Macro - more compatibility with Operation
- Operation - value patch
- Prevent empty macros
- Mispackaged Bloc method

Merging Improvements

---

source/Magritte-GToolkit/MAActionDescription.extension.st
source/Magritte-Model/MAActionDescription.class.st

- Use Gt Icon, and then Icon as a fallback
- Respect isLabelVisible
- Respect enableBlock - currently omits button, not very dynamic!

GT Action Improvements

---

source/Magritte-Model/MATPropertyOwner.trait.st

Was always a stretch to put there. Now part of Objective-Lepiter project

[Clean]: Remove UUID Stuff From PropertyOwner Trait

---

.github/workflows/runTests.yaml
source/BaselineOfMagritte/BaselineOfMagritte.class.st

- removed GT loading
- upgraded grease to 1.8

- added pharo10 platform attribute section

---

source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-GToolkit/MATokenCollectorElement.class.st
source/Magritte-GToolkit/MATokenElement.class.st
source/Magritte-GToolkit/MATokenRequest.class.st
source/Magritte-GToolkit/MATokenSelectorElement.class.st

Reasonable v 1.0. Works nicely for ToOne and ToMany Relations. Probably could be extended to options as well

Spotter for Multiple Relation Descriptions

---

source/Magritte-GToolkit/MATokenElement.class.st

And remove a dummy action from spike

[Enh]: Token Element (via Token Selector & Collector) - Custom Context Menu Actions

---

source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-UI/MATContainerPresenter.trait.st

Sometimes you want to commit even though the object doesn't pass validation

[Enh]: UI Force Action

---

source/Magritte-GToolkit/MATokenSelectorElement.class.st

- put search button on left so it is never out of view
- honor description `#display:`

[Enh]: Bloc Token Display

---

source/Magritte-GToolkit/MATokenSelectorElement.class.st

- `send:` block wasn't being honored
- simplify code

[Port]: Token Selector to GT Streaming Spotter

---

source/BaselineOfMagritteForGToolkit/BaselineOfMagritteForGToolkit.class.st
source/BaselineOfMagritteForGToolkit/package.st
source/Magritte-Model/MAActionDescription.class.st
source/Magritte-Model/MADescriptionContext.class.st
source/Magritte-Model/MAElementDescription.class.st
source/Magritte-Model/MAPragmaBuilder.class.st
source/Magritte-Morph/MorphicUIManager.extension.st

Hopefully resolves https://github.com/magritte-metamodel/magritte/pull/321 and https://github.com/magritte-metamodel/magritte/pull/267. Made a new PR because I wasn't sure how to cherrypick from existing PRs. @JurajKubelka

Gt changes cherrypick

---

source/Magritte-GToolkit/GtPhlowProtoView.extension.st
source/Magritte-GToolkit/MAElementDescription.extension.st
source/Magritte-Model/MAElementDescription.class.st

Add columns to a gt list for each described field

[Enh] GT columns from desc

---

source/Magritte-Model/MATPropertyOwner.trait.st

Trying to keep the API small, but needed this in real world use

[Enh]: UUID Property Setter

---

source/Magritte-GToolkit/Object.extension.st

[Enh]: GT Form - Add "Inspect Memento" Button

---

source/Magritte-GToolkit/GtPhlowProtoView.extension.st

Previously Container was auto-generated from a class and could not be modified.

[Enh]: GT Columned List View from Container

---

source/Magritte-GToolkit/GtPhlowProtoView.extension.st

Remove special method accepting a container

[Enh]: GT Columned View from Description - Simplify API

---

source/Magritte-GToolkit/Object.extension.st

... where real work seems to happen now

[Port]: GT Actions Hook - Move from gtActions to gtActionsInContext:

---

source/BaselineOfMagritte/BaselineOfMagritte.class.st

Wondering if that will cut down on image size when loaded. Tally showed many strings that seem Metacello-related

[MetaC]: Change Strings to Symbols

---

source/Magritte-GToolkit/MABrTextEditor.class.st
source/Magritte-GToolkit/MAElementBuilder.class.st
source/Magritte-GToolkit/MAFieldElement.class.st
source/Magritte-GToolkit/MAGtInputFieldAptitude.class.st

Give feedback while user types, showing whether input is valid.

[Enh]: Dynamic Form Validation in GT Bloc

---

source/Magritte-Merging/MAPatchMacro.class.st
source/Magritte-Merging/MAPatchOperation.class.st
source/Magritte-Model/MAStringReader.class.st

Logic was duplicated when visiting both elements and time. Includes some unrelated GT view enhancements

[Refactor]: Str Reader - Extract Object Read from Kind
