magritte-metamodel/magritte

- source/Magritte-Seaside.package/MAContainerDecoration.class/instance/execute..st
For example, in `aComponent addValidatedForm: { [ self register ] -> 'Register' };`, the block doesn't require and argument
> [Enh]: Fix #70 - Decoration Blocks - Component Arg Should Be Optional

- source/Magritte-Model.package/MASelectorAccessor.class/instance/fieldDescription.st
Sometimes you need a string representation of a field. For SelectorAccessors, it could easily be the readAccessor, for ChainAccessors maybe `firstSelector:secondSelector`, etc.
> [Enh]: Fix #72 - Add `#fieldDescription`

- source/Magritte-Model.package/Collection.extension/instance/maAllOptionsFor..st
- source/Magritte-Model.package/Collection.extension/instance/maSelectMatching..st
- source/Magritte-Model.package/MADynamicOptions.class/class/block..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/block..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/block.st
- source/Magritte-Model.package/MADynamicOptions.class/instance/detect..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/includes..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/includesBlock..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/includesBlock.st
- source/Magritte-Model.package/MADynamicOptions.class/instance/maAllOptionsFor..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/maSelectMatching..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/reader..st
- source/Magritte-Model.package/MADynamicOptions.class/instance/reader.st
- source/Magritte-Model.package/MADynamicOptions.class/properties.json
- source/Magritte-Model.package/MAOptionDescription.class/instance/allOptions.st
* e.g. options are results from Google Places matching the input
* Override PluggableTextFieldMorph while [discussing on mailing
* list](http://forum.world.st/PluggableTextFieldMorph-Entry-Completion-Enhancement-td4901577.html)
* Based on Magritte-Model-SeanDeNigris.468
Dynamic Options: Allow Optimized Completion Objects
Google Places, for example, uses one lightweight object for
autocompletion, and another with full details.
We offer a mapping between the object we're using for completion, and
the object it really represents (that should be ultimately stored)
> Fix #79 - Dynamic Options

- source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline310CommonExtDeps..st
We only needs the Core group from Seaside. 
Fixes #94
> 94-Is-there-a-reason-to-have-so-many-groups-from-Seaside

- source/Magritte-Model.package/MADescription.class/instance/tryValidation.ifPass..st
- source/Magritte-Model.package/MAMultipleOptionDescription.class/instance/validateKind..st
- source/Magritte-Model.package/MATableDescription.class/instance/validateChildren..st
- source/Magritte-Model.package/MATableDescription.class/instance/validateCounts..st
- source/Magritte-Model.package/MATableDescription.class/instance/validateSpecific..st
- source/Magritte-Model.package/MAToManyRelationDescription.class/instance/validateKind..st
- source/Magritte-Model.package/MAValidationError.class/instance/isResumable.st
- source/Magritte-Model.package/MAValidatorVisitor.class/instance/validate.using..st
- source/Magritte-Model.package/MAValidatorVisitor.class/instance/visitContainer..st
- source/Magritte-Model.package/MAVisitor.class/instance/visit..st
- source/Magritte-Tests-Model.package/MADescriptionTest.class/instance/should.raiseSingle..st
- source/Magritte-Tests-Model.package/MADescriptionTest.class/instance/should.raiseSingle.withExceptionDo..st
- source/Magritte-Tests-Model.package/MAElementDescriptionTest.class/instance/testValidate.st
- source/Magritte-Tests-Model.package/MAElementDescriptionTest.class/instance/testValidateConditions.st
- source/Magritte-Tests-Model.package/MAElementDescriptionTest.class/instance/testValidateMultipleFailures.st
- source/Magritte-Tests-Model.package/MAMagnitudeDescriptionTest.class/instance/testRangeErrorMessage.st
- source/Magritte-Tests-Model.package/MAMagnitudeDescriptionTest.class/instance/testValidateSpecific.st
In many cases, one failure would return without looking for others
> [Enh]: Validation Should Aggregate All Failures

- source/Magritte-Model.package/MAChainAccessor.class/instance/descriptionAccessor.st
- source/Magritte-Model.package/MADelegatorAccessor.class/instance/descriptionNext.st
- source/Magritte-Model.package/MADescription.class/instance/descriptionAccessor.st
- source/Magritte-Model.package/MASelectorAccessor.class/instance/descriptionSelector.st
- source/Magritte-Model.package/MAStringWriter.class/instance/visitClassDescription..st
Example:
Given aDescription, like `MABooleanDescription new.`, you can now define an accessor via Magritte (e.g. a Morphic form).
As a test, let's try to use our description to read `Smalltalk os isMacOSX`:
1. In a MA Morphic form, click "Remove" for the current null accessor.
2. Now choose `MAChainAccessor` from the dropdown
3. In the popup form:
a. For the first accessor, choose `MASelectorAccessor` the dropdown and fill "os" into the edit field
b. For the second accessor, choose `MASelectorAccessor` the dropdown and fill "isMacOSX" into the edit field
Now, DoIt: `myDescription read: Smalltalk` "==> true | false"
> [Feature]: Resolve #49 - Meta-Described Accessors

- source/Magritte-Model.package/MABlockDescription.class/class/defaultKind.st
- source/Magritte-Model.package/MABlockDescription.class/class/defaultMorphClasses.st
- source/Magritte-Model.package/MABlockDescription.class/class/isAbstract.st
- source/Magritte-Model.package/MABlockDescription.class/class/label.st
- source/Magritte-Model.package/MABlockDescription.class/instance/acceptMagritte..st
- source/Magritte-Model.package/MABlockDescription.class/properties.json
- source/Magritte-Model.package/MAStringReader.class/instance/visitBlockDescription..st
- source/Magritte-Model.package/MAVisitor.class/instance/visitBlockDescription..st
*NB*: Conversion from string requires code evaluation, which can pose a big security risk. Use with caution.
We duplicated MAMemoDescription's multi-line behavior. It would be nice to extract into a Trait to avoid the duplication, but we'll hold off in the interest of cross-platform compatibility since it's "just a few methods"
Fix Issue #97
> [Enh]: Smalltalk Block Description

- source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline310CommonExtDeps..st
Magritte currently depends on the old version of Seaside and Grease. The version of Seaside is bugged. 
Here is a PR to fix that.
> Update Seaside and Grease versions

- source/Magritte-Model.package/Object.extension/instance/magritteAllDescriptionsFor..st
- source/Magritte-Model.package/Object.extension/instance/magritteAlternatesFor..st
What if our object has a field that can be thought of in different ways? For example, a messages field that can be filtered into `#read`, `#unread`, and `#all`. `#descriptionMessages` would be the actual description, and then there could be a `#descriptionUnreadMessages` and `#descriptionReadMessages` which are descriptions of the filtered collections. By annotating these alternate descriptions with `<magritteAltFor: #descriptionMessages>`, these could be e.g. displayed as tabs in a Magritte form.
> Fields with Multiple Aspects (i.e. Alternate Descriptions)

- source/Magritte-Glamour.package/MAElementDescription.extension/instance/glmPresentation..st
- source/Magritte-Glamour.package/MAElementDescription.extension/instance/glmPresentation.st
Glamour Presentations: Allow Disable 
- Usage: `aDescription glmPresentation: nil`
- Add method comment describing API including this addition
> feature_glm-presentation-disable

- source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline310CommonExtDeps..st
- source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline330ForPharo..st
Updated baseline so that Magritte loads correctly into Pharo 9 and load current version of Grease (1.5.x) that will be compatible with Pharo 9 (is not yet, but Grease PR is being reviewed: https://github.com/SeasideSt/Grease/pull/99 ).
Solves #141
> Updated for Pharo 9

- source/Magritte-Developer.package/Object.extension/class/maAddField.with..st
- source/Magritte-Morph.package/MAMemoMorph.class/instance/buildMorphView.st
- source/Magritte-Morph.package/TokenCollectorMorph.class/instance/accept..st
- When adding field, list description classes ascending alpha
- Use RubPluggableTextMorph for MemoMorphs (it replaced PluggableTextMorph in P9 per http://forum.world.st/pharo8-api-change-newTextEditor-tt5112654.html) <- this one is the only change that seems not to be infinitely backward compatible. It works in P8 for sure. I say we let it go and see if anyone complains?! I always wonder if there are even users of super old platforms using our code...
- TokenCollectorMorph was comparing text to string
> [Bug]: Fixes for Pharo 9

- source/Magritte-Model.package/MAElementDescription.class/instance/printFor.on..st
- source/Magritte-Model.package/WriteStream.extension/instance/maPrint.for..st
- source/Magritte-Model.package/WriteStream.extension/properties.json
- source/Magritte-Tests-Model.package/MAExtensionsTest.class/instance/testPrintingConvenience.st
Typically, `#printOn:` and friends have a lot of nil checks sprinkled around. Modern Pharo's tools are typically robust to printString errors, but you still get a not-very-helpful "error printing" message. Here comes Magritte to the rescue with `WriteStream >> #maPrint:for:`. 
Here's an example:
```smalltalk
printOn: aStream
aStream 
maPrint: self descriptionDescription for: self;
nextPutAll: 'whatever'.
```
This reads the value and behaves gracefully if it is unset (by doing nothing). Notice that it also fits into the typical cascade without breaking it into multiple statements.
Without this the options are not as nice...
Nil checks everywhere...
```smalltalk
printOn: aStream
description ifNotNil: [ :desc | aStream nextPutAll: desc ]
"repeated for each relevant field"
```
You might just …
> Printing Convenience, Including a Test

- source/BaselineOfMagritte.package/BaselineOfMagritte.class/instance/baseline330..st
Accidentally loading MADescription extension methods before the class
> [bug]: MetaC - Invert Dependency bet. Model and Deprecated3dot7

- source/Magritte-Model.package/MAContainer.class/instance/print.on..st
- source/Magritte-Model.package/Object.extension/instance/maPrintOn..st
Allows customization without Object API explosion
> Refactor - Move #maPrintOn: to Container

- source/Magritte-Model.package/MAStringReader.class/instance/isFalseUsing..st
- source/Magritte-Model.package/MAStringReader.class/instance/isTrueUsing..st
- source/Magritte-Model.package/MAStringReader.class/instance/visitBooleanDescription..st
- source/Magritte-Tests-Model.package/MABooleanDescriptionTest.class/instance/testCaseInsensitiveStrings.convertTo..st
- source/Magritte-Tests-Model.package/MABooleanDescriptionTest.class/instance/testFalseStrings.st
- source/Magritte-Tests-Model.package/MABooleanDescriptionTest.class/instance/testTrueStrings.st
- e.g. both 'f' and 'F' should be read as `false`
- Add a test; fails without fix and passes with
- Changed for default strings, but explicitly set string (e.g. via `#falseString:` still compared via #= because it's not clear what user intention would be in that case; may change in the future based on experience
> Boolean String Reading Should Be Case Insensitive

- source/Magritte-GToolkit.package/GtDocument.extension/class/maFor.using..st
- source/Magritte-GToolkit.package/GtDocument.extension/properties.json
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/description..st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/description.st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/object..st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/object.st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/read..st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/rootDirectory.st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/instance/save..st
- source/Magritte-GToolkit.package/MAGtDescriptionStorageStrategy.class/properties.json
Similar to ${class:GtDocumenter}$''s built-in ability to store documents in class comments via ${method:GtDocument class>>#forClass:}$, you can view and edit fields described by ${class:MAStringDescription}$. For example: ==GtDocument maFor: recipe using: self noteDescription.==
> Feature: GtDocument from anMAStringDescription

- source/Magritte-GToolkit/GtDocumenter.extension.st
- source/Magritte-GToolkit/GtDocumenterEditor.extension.st
- source/Magritte-GToolkit/GtDocumenterEditorStorageModel.extension.st
- source/Magritte-GToolkit/MAGtDescriptionStorageStrategy.class.st
- GtDocument has been deprecated in favor of GtDocumenter
- Much of this code was originally committed in 80b6611, but after several merges, by cc476c1 it was missing
> Gt Document Support: Update Due to GT Deprecation

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Not generally applicable (e.g. gemstone) but we'll wait until someone complains.
This is needed due to the recent Morphic presenter renames. The old names are in the monolithic deprecated package. If needed, this could be split up into a separate Morphic-Deprecated or similar, but this PR will get the code loadable again.
> [MetaC]: Deprecated Package Req. Morph

- source/Magritte-Model/MADescription.class.st
- source/Magritte-Model/MASingleOptionDescription.class.st
- source/Magritte-Model/Object.extension.st
- source/Magritte-Tests-Model/MAElementDescriptionTest.class.st
This allows integration with e.g. the Null Pattern. For example, let's say that my domain has a name with a single-option relation to a generational (e.g. Jr, Sr). Since generationals are optional, there is NullGenerational to avoid nil checks everywhere. Before this fix, there was no way to inject that class instead of nil. Now, there is. See the test (#testUndefinedValue).
> [Enh]: Description `undefinedValue` Property

- source/Magritte-Model/MAValidatorVisitor.class.st
- source/Magritte-Tests-Model/MAValidatorVisitorTest.class.st
It was still using a nil guard, so custom `undefinedValue` would signal a kind error.
> [bug]: Validator - Update for Undefined Value (and a Test)

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Fixes (as far as Pharo) #144, but still waiting on Gemstone...
- We will only support Pharo 6+
N.B. Tried to reverse dependency between Model and Pharo-Model, but MAExternalFileModel depends on MAFileModel (superclass)
> Simplify and Update Baseline

- source/Magritte-GToolkit/MADropdownElement.class.st
- source/Magritte-GToolkit/MAElementBuilder.class.st
- source/Magritte-Model/MADescription.class.st
- source/Magritte-Model/MAElementDescription.class.st
- source/Magritte-Model/MAOptionDescription.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
- source/Magritte-Morph/MAElementRow.class.st
- source/Magritte-Morph/MAMorphicDate.class.st
- source/Magritte-Morph/MAMorphicFile.class.st
Still in the process of fully integrating element #display: with references. There were a lot of places using #displayStringFor: directly, which is used internally by the string reader/writer and should probably best be used that way to avoid sprinkling implementation details all over the place.
> [Bug]: Reference to String

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Groups not well-supported by tools and group only had one package and so limited usefulness
> [MetaC]: Remove Morphic Group

- source/Magritte-Model/MADescription.class.st
- source/Magritte-Model/MADirectoryDescription.class.st
- source/Magritte-Model/MASelectorAccessor.class.st
It can often be useful for a description to have a canonical name. For some accessors there is an obvious default e.g. read selector or variable name.
Descriptions *did* have a "name", but it was really a string explaining the type of the description itself e.g. "1:M..." for to-many descriptions. 
Here, we rename the existing `#name` behavior to `#type` and reimplement `#name` as a configurable canonical specifier.
> [Enh]: Descriptions - Real Names

- source/Magritte-Model/MAAccessor.class.st
- source/Magritte-Model/MAChainAccessor.class.st
- source/Magritte-Model/MADelegatorAccessor.class.st
- source/Magritte-Model/MADictionaryAccessor.class.st
- source/Magritte-Model/MASelectorAccessor.class.st
Some weren't, leading to a DNU when looking up field names e.g. when inspecting a description
> [Bug]: All Accessors Should Implement `#name`

- source/Magritte-Model/MAChainAccessor.class.st
- source/Magritte-Tests-Model/MAChainAccessorTest.class.st
Per the class comment: "To read and write a value the ==accessor== is performed on the given model and the result is passed into the ==next== accessor."
However, the implementation was using the ==next== accessor *first* instead of last.
Having trouble committing the fixes to the tests so there will likely be at least one more commit for this.
> [Bug]: Chain Accessors Fields Flipped

- source/Magritte-GToolkit/MACompositeElementBuilder.class.st
- source/Magritte-GToolkit/MADescription.extension.st
- source/Magritte-GToolkit/MADropdownElement.class.st
- source/Magritte-GToolkit/MAElementBuilder.class.st
- source/Magritte-GToolkit/Object.extension.st
- source/Magritte-Model/MAChainAccessor.class.st
- source/Magritte-Model/MACheckedMemento.class.st
- source/Magritte-Model/MACompositeAccessor.class.st
- source/Magritte-Model/MACompositeConflict.class.st
- source/Magritte-Model/MADelegatorAccessor.class.st
- source/Magritte-Model/MAMemento.class.st
- source/Magritte-Morph/MAContainer.extension.st
This might be more trouble than it's worth, but it "works" and is a test of the extensibility of the visitor builder(s), so we'll keep it until we have something better.
- Composite Element Builder and example(s)
- `MADescription>>#blocClass`, just like `#morphicClass`
- Make dropdown element polymorphic with Editor Element RE initial string
- Element Builder
- Add Diff Column
- [Port]: Update some look -> aptitude stuff
- Form column headers
- Cache description; not sure if really needed since gets passed to `#visit:`, but makes it convenient that we don't need to pass it everywhere e.g. `presenterUsing: aDescription`
- Examples
- Object `#magritteElementBuilder` - honor container's prefered class
- Chain Accessor - default label
- [Feature]: Composite Accessor/Conflict
- [Doc]: Class …
> Fix #221: Composite Form Element

- source/Magritte-Merging/MAPatchMacro.class.st
- source/Magritte-Merging/MAPatchMacroElement.class.st
- source/Magritte-Merging/MAPatchOperation.class.st
- Examples
- Cache Old Value for All Creation Paths; We were doing it only from instance creation method, but this won't work e.g. via metamodel
- Macros
- Add operation(s) dynamically
- Better view (expand/collapse w descriptive header)
- [Clean]: Replace unused and nonsensical `model` with `receivers`
- [Enh]: Better printing
- Element
> Patches - Flesh out GT Support

- source/Magritte-Merging/MAPatchMacro.class.st
- source/Magritte-Merging/MAPatchOperation.class.st
If an operation changes the old value to the same value, ignore it
> [Enh]: Patches should Ignore No-Ops

- source/Magritte-Model/MARelationDescription.class.st
- source/Magritte-Morph/MAElementRow.class.st
For relation descriptions, the default reference was overridden to nil. Not sure why that was, but tests still pass removing the override.
> Fix #234 - MAElementRow Should Use Reference

- lepiter/cuv8kex3dqlfsb604nb7ytijp.bak
- source/Magritte-GToolkit/MAActionDescription.extension.st
- source/Magritte-GToolkit/Object.extension.st
- Valuable passed to `#gtAction:` now gets Null Phlow Action instead of a button. Let's see if it's annoying to manually set the icon and label. Another option would be to pass a partially configured button, because Phlow seems to let you create any type of action from any other.
- Docs - method comments and Lepiter
-  Rename `gtActionFor:` (which means something else, see implementors) to `#gtActionOf:`
> Enh gt action flexibility

- source/Magritte-Model/MAObjectUIDReference.class.st
Check species to avoid errors from deep in the system e.g. during Lepiter materialization
> [Enh]: Object ID Ref - More Robust Equality

- source/Magritte-Model/MATPropertyOwner.trait.st
Sometimes instead of storing nil in the dictionary, you'd rather just remove the key
> [Enh]: Property Put or Remove Nil

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Currently in Pharo 10, only a few tests pass because Magritte uses a previous version of Grease (Grease:v1.8.x)
> 1727 ran, 126 passed, 0 skipped, 0 expected failures, 0 failures, 1601 errors, 0 passed unexpected
This PR update the Baseline to use Grease:v1.9.0 and all tests pass now:
> 1727 ran, 1727 passed, 0 skipped, 0 expected failures, 0 failures, 0 errors, 0 passed unexpected.
To reproduce it in a clean Pharo 10 image:
```smalltalk
EpMonitor disableDuring: [ 	
Metacello new
baseline: 'Magritte';
repository: 'github://hernanmd/magritte:pharo10-ready/source';
load: 'Tests' ].
```
And run the Magritte tests
> PR for green build in Pharo 10

- source/Magritte-GToolkit/MAElementBuilder.class.st
- source/Magritte-GToolkit/MATokenCollectorElement.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
Nice way to choose from available objects, or even add a new one, depending on the spotters that are passed. It'd be nicer to utilize auto-complete, as opposed to the current button, but it seems GT currently only has auto-complete for code editors, not all text editors.
> [Feature]: Bloc ToOne Relations Spotter Support

- source/Magritte-Model/MACachedMemento.class.st
- source/Magritte-Model/MAMemento.class.st
Currently, the cache stores the actual collection from the described object. If the cache's collection is modified, the object is modified too. This invalidates the protection of the cache.
NB. Includes type check. This is WIP because it may need to be extended to options. Once that is clear, we'll remove the type check
> [Bug]: Cached Memento Should Copy ToMany Collections

- source/Magritte-GToolkit/MAGtDelegatedSearch.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
Let's say you have a person object with an `addresses` field. In a person's Magritte form, you want to have Spotter completion to create new addresses. What makes this a bit special is that an address probably doesn't live in a special collection, so there is probably no object that defines a suitable Spotter.
By doing `anMAReferenceDescription gtSearchDelegateTo: anObject message: aSymbol`, you can have any object stand in to supply the Spotter
> [Feature]: Reference GT Searches - Delegate to another object

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
- Order platform blocks chronologically descending by release date
- drop support for Pharo 6
- Fix platform package aliases
> [MetaC]: Fix Baseline for Pharo 9 and 10

- source/Magritte-GToolkit/MAElementBuilder.class.st
- source/Magritte-Morph/MAContainer.extension.st
Also, builder - Don't Actually Build unless Asked. `#elementBuilderFor:` was actually visiting instead of just initializing, which limited customization potential
> Bloc Form Editor Completion

- source/Magritte-Model/MACachedMemento.class.st
- source/Magritte-Model/MACheckedMemento.class.st
- source/Magritte-Model/MAMemento.class.st
Otherwise changes to the model can bleed through to the "original" dictionary
> [Bug]: Checked Memento "Original" Should Copy Collections

- source/Magritte-Model/MACachedMemento.class.st
- source/Magritte-Model/MACheckedMemento.class.st
- source/Magritte-Model/MAMemento.class.st
- source/Magritte-Tests-Model/MACachedMementoTest.class.st
- source/Magritte-Tests-Model/MACheckedMementoTest.class.st
For example, to check if the model has changed elsewhere, it does:
```smalltalk
self isDifferent: self original to: self pullRaw
```
But if the field values were not copied, this seemingly has no meaning for complex objects, because any changes to them from outside will be reflected equally in the `original` dictionary. E.g. if `original at: #person == self model person` and outside someone does `self model person age: 25`the check above will pass even though it should fail.
> [Bug]: Cached Memento Should Copy Fields

- source/Magritte-Morph/MAElementRow.class.st
- source/Magritte-Morph/MAMorphicCheckbox.class.st
- source/Magritte-Morph/MAMorphicDate.class.st
- source/Magritte-Morph/MAMorphicDropList.class.st
- source/Magritte-Morph/MAMorphicMultiSelectList.class.st
- source/Magritte-Morph/MAMorphicOneToMany.class.st
- source/Magritte-Morph/MAMorphicOneToOne.class.st
- source/Magritte-Morph/MAMorphicRelation.class.st
- source/Magritte-Morph/MAMorphicText.class.st
- source/Magritte-Morph/SpDatePresenter.extension.st
- source/Magritte-Morph/TokenCollectorMorph.class.st
- source/Magritte-Morph/TokenMorph.class.st
Multiple fixes and updates for Pharo 10, incl. usage of Spec2 instead of Spec1.
Partially fixes https://github.com/magritte-metamodel/magritte/issues/294
Makes Magritte compatible with Pharo 10+, but **incompatible with Pharo 8-**. Might be advisable to create separate branch for Pharo 10+ or Pharo8-
> Updates for Pharo 10

- source/Magritte-GToolkit/MATokenSelectorElement.class.st
- source/Magritte-Model/MAMemento.class.st
- source/Magritte-Model/Object.extension.st
As a result of #296, memento fields are copies of the model state. Bloc tokens were not updated to this new strategy, and thus were pointing to these copies instead of the actual state. When they were clicked, an inspector would open on a temporary copy, not the object actually held by the model.
> [Bug]: Bloc Form To-One Tokens Pointing to Copy

- source/Magritte-GToolkit/MATokenSelectorElement.class.st
- source/Magritte-Model/MACheckedMemento.class.st
- source/Magritte-Model/MAMemento.class.st
- source/Magritte-Model/Object.extension.st
We were *always* copying field values when pulling so that the `original` could query whether the model had changed elsewhere. However, this created complication in other contexts (e.g. display of current data) where you want the real objects. So we simplify and only copy for the one use case where we currently need it (otherwise just use the real objects)
> [Enh]: Mementos - Only Copy Checked Original

- source/Magritte-Model/MATPropertyOwner.trait.st
Just leave in main package to prevent combinatorial explosion of platform packages. Doesn't references any GT-specific classes
> [Enh]: GT Spotter for Properties

- source/Magritte-GToolkit/MATokenSelectorElement.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
For reference descriptions, a way to supplement the send block of a gt search source. Useful e.g. if you need to establish a parent/child relationship or do other configuration not anticipated by the source spotter writer
> [Enh]: GT Search Transform

- source/Magritte-GToolkit/MADropdownElement.class.st
- source/Magritte-GToolkit/MATokenSelectorElement.class.st
We don't yet have a flexible mechanism to adjust the display string/text via the description, as described by #310 and #311, so use `#gtDisplayText` for now, which at least is better than a print string
> [WIP]: Bloc Token Labels - Use Display String

- source/Magritte-GToolkit/MATokenSelectorElement.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
Revert 71bca39 because one can use the MAContainer reference trick hinted at by the comment of comment MARelationDescription>>#reference and fleshed out by Lukas (see MAReferenceDescription class comment)
> Bloc Relation Tokens - Use String Writer

- source/Magritte-Model/MATPropertyOwner.trait.st
We had extracted this to ObjectiveLepiter, the only user. However, due to limitations in Pharo packaging, namely lack of extension traits, users become unusable unless in GT, where OL works. For now, it seems prudent to live with the two methods in question to make life easier
> Property Owner - Restore UUID Support

- source/Magritte-Model/MAStringWriter.class.st
- Container should consider more than one field
- Relations should use reference description, not that of object refered to
> [Bug]: Fix String Writer for References

- README.md
- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Modified baseline to make Magritte loadable in Pharo 11 and 12 and modified README to mention Pharo 9+.
Yet loadable does not mean fully working and tested. It works in Pharo 11 for OpenPonk that uses small subset of Magritte features, but nothing else was actually used there.
> Made loadable in Pharo 11 and 12

- source/Magritte-Model/MATPropertyOwner.trait.st
UID stuff moved out of `MATPropertyOwner`
> [Clean]: Extract UID Property Support to Dynabook Foundation

- source/Magritte-Model/MADescription.class.st
- source/Magritte-Model/MAElementDescription.class.st
- Slightly different than `default`. Default is what the value of the field *is* if not explicitly set. The initial answer is what the value *might be* e.g. to make it easier to fill out a form.
- Also remove a duplicated statement that was a no-op
> [Enh]: Element Descriptions - Initial Answer

- lepiter/d7hyk2iipxwmivsgijclbq2y0.bak
- lepiter/d7hyk2iipxwmivsgijclbq2y0.lepiter
- source/Magritte-Model/MACachedMemento.class.st
- source/Magritte-Model/MACheckedMemento.class.st
- source/Magritte-Model/MAElementDescription.class.st
- source/Magritte-Model/MAMemento.class.st
- source/Magritte-Model/MAOptionDescription.class.st
- source/Magritte-Model/MAReferenceDescription.class.st
- source/Magritte-Model/MAStraightMemento.class.st
- source/Magritte-Model/MAToManyRelationDescription.class.st
- source/Magritte-Tests-Model/MACheckedMementoTest.class.st
- source/Magritte-Tests-Model/MADescriptionBuilderTest.class.st
- source/Magritte-Tests-Model/MAMementoTest.class.st
- source/Magritte-Tests-Model/MAMockAddress.class.st
Hopefully finally resolves a buffet of related issues (and PRs) mentioned below...
The problem is that mementos were copying described values in two places: 
```smalltalk 
MACachedMemento>>cookRawPull: aDictionary
super cookRawPull: aDictionary.
aDictionary keysAndValuesDo: [ :key :value |
| isCollectionOfRelations | isCollectionOfRelations := value isCollection and: [ key isKindOf: MAToManyRelationDescription ]. isCollectionOfRelations ifTrue: [  aDictionary at: key put: value copy ] ].
```
There are several problems with the above: Firstly, it is applied to cached mementos. This overly broad, since the motivating problem affects the `original` dictionary - something only checked mementos have. Even worse, it applies to all pulls, not just those to `original` dictionaries. This lead to a …
> Cached Mementos - To Copy or Not To Copy?

- source/Magritte-Model/MAActionDescription.class.st
We were only looking at part of the state - species and action - which caused some actions to overshadow others. In fact, since these are mutable, we are better off sticking with identity comparison. Supersedes #345
> [Bug]: action comparison

- source/Magritte-Model/MAValidatorVisitor.class.st
- source/Magritte-Model/MAVisitor.class.st
For some reason, it was implemented in MAVisitor, even thought it doesn't apply to any other subclass
> [Clean]: Validation Error Catching should be in Validator Visitor

- source/Magritte-Model/MATPropertyOwner.trait.st
There were two problems:
1. presentBlock expects an argument but none is given
2. The announcement was triggered in the presentBlock, but should be in the absentBlock
> [Bug]: Property Owner Trait - Only Announce Change After Put

- source/BaselineOfMagritte/BaselineOfMagritte.class.st
Allows loading into Pharo 12.
May help with https://github.com/magritte-metamodel/magritte/issues/342#issuecomment-1975193958 (not with the original issue, just the unrelated problem in the linked comment)
> Updated Grease to v1.18.0

- source/Magritte-Developer/MADeveloperTests.class.st
- source/Magritte-Developer/MASelectorAccessor.extension.st
- source/Magritte-Developer/Object.extension.st
- source/Magritte-Model/MAElementDescription.class.st
- source/Magritte-Model/MANullAccessor.class.st
- source/Magritte-Model/Object.extension.st
- source/Magritte-Tests-Model/MAStraightMementoTest.class.st
Includes a test that fails before and passes after the fix
> [Bug]: Description Generation - Don't Write Null Accessors

- source/Magritte-Model/MAMessagingStringWriter.class.st
Enables delegating string writing to an arbitrary object via any of its messages. 
*Limitation:* cannot be used when 1) the message receiver is the container and 2) descriptions are cached e.g. when using the description for the first object in a homogeneous collection for the whole collection.
Here is an example (which illustrates No. 1 in the limitation above and so wouldn't work with a cached description):
```
MyDomainClass>>employeeDescription
<magritteDescription>
| message writer reference |
message := MessageSend 
receiver: self
selector: #employeeDisplayString.
writer := MAMessagingStringWriter new
messageSend: message.
reference := MAContainer new 
stringWriter: writer;
yourself.
^ MAToOneRelationDescription new
reference: reference;
accessor: #employee;
yourself
```
> [Enh]: MAMessagingStringWriter

- source/Magritte-Model/MANumberDescription.class.st
- source/Magritte-Model/MAStringReader.class.st
- source/Magritte-Tests-Model/MANumberDescriptionTest.class.st
Reads strings like `10,000` (the default) or change to `10.000`
> [Enh]: Number Reading - Thousands Separators

- source/Magritte-GToolkit/MATokenSelectorElement.class.st
Before, if there were many multiple options or to-many relation items, they would often run off the screen and get clipped:
After, they flow down to stay within the container horizontally:
> [Enh]: GT Form Tokens should Flow

- source/Magritte-GToolkit/MAElementBuilder.class.st
- source/Magritte-GToolkit/Object.extension.st
- After saving, forcing, or cancelling a form, reset the fields.
- Element builder now caches the toolbar after creation so that it can be easily customized from outside.
> [Enh]: In GT Views, Reload Forms after Button Actions

- source/Magritte-Model/MAConjunctiveCondition.class.st
Right now, "and" conditions use `allSatisfy:`. This means that every condition will be evaluated. The problem arises with this common pattern: `[ anObject isSafe ] and: [ anObject doRiskyThing ]`, which relies on the second test not being performed if the first fails.
> [Bug]: "And" Conditions should Fail Quickly
